name: CICD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - uses: bahmutov/npm-install@v1
      - run: npm run validate
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - uses: bahmutov/npm-install@v1
      - run: npm test -- --ci
      - shell: bash
        run: |
          curl -s -o codecov https://codecov.io/bash \
            && VERSION=$(grep 'VERSION=\".*\"' codecov | cut -d'"' -f2) \
            && shasum -a 512 -c --ignore-missing <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA512SUM)
      - shell: bash
        run: |
          chmod +x codecov
          ./codecov
  e2e:
    name: E2E
    needs: [format, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - uses: bahmutov/npm-install@v1
      - uses: wbeuil/wait-for-deployment@v1.0.0
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          CYPRESS_BASE_URL: ${{ steps.deployment.outputs.url }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
